=== mariaserena/DP_Assignments/lab1/temp413981609/xsd/nfvInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
xmlns:tns="http://NFV.dp2.polito.it" 
targetNamespace="http://NFV.dp2.polito.it" 
elementFormDefault="qualified">

<element name="dp2_nfv" type="tns:dp2_nfvType">
<!-- the nffg is characterized by a name which uniquely identifies it -->
	<key name="nffg_name_key">
		<selector xpath="tns:nf_fg"/>
		<field xpath="@name"/>
	</key>
	<!-- the nffg this node is associated on -->
	<keyref name="nffg_name_keyref" refer="tns:nffg_name_key">
		<selector xpath="tns:nf_fg/tns:node"/>
		<field xpath="@nffg_name"/>
	</keyref>	
	<!-- each VNFT has a name which uniquely identifies it inside the catalog -->	
	<key name="fun_type_key">
		<selector xpath="tns:catalog/tns:VNFT"/>
		<field xpath="@name"/>
	</key>
	<keyref name="fun_type_keyref" refer="tns:fun_type_key">
		<selector xpath="tns:nf_fg/tns:node"/>
		<field xpath="@VNFT"/>
	</keyref>
	
	<!-- each node has a name which is unique -->
	<key name="node_name_key">
		<selector xpath="tns:nf_fg/tns:node"/>
		<field xpath="@name"/>
	</key>
	<keyref name="node_name_keyref" refer="tns:node_name_key">
		<selector xpath="tns:in/tns:host"/>
		<field xpath="tns:node"/>
	</keyref>
	<keyref name="snode_name_keyref" refer="tns:node_name_key">
		<selector xpath="tns:nf_fg/tns:node/tns:link"/>
		<field xpath="@source_node"/>
	</keyref>
	<keyref name="dnode_name_keyref" refer="tns:node_name_key">
		<selector xpath="tns:nf_fg/tns:node/tns:link"/>
		<field xpath="@dest_node"/>
	</keyref>
	
	<unique name="link_name_key">
		<selector xpath="tns:nf_fg/tns:node/tns:link"/>
		<field xpath="@name"/>
	</unique>
	
	
	<key name="host_key">
		<selector xpath="tns:in/tns:host"/>
		<field xpath="@name"/>
	</key>
	<keyref name="host_keyref" refer="tns:host_key">
		<selector xpath="tns:nf_fg/tns:node"/>
		<field xpath="tns:host"/>
	</keyref>
	<keyref name="shost_keyref" refer="tns:host_key">
		<selector xpath="tns:in/tns:connection"/>
		<field xpath="@host1"/>
	</keyref>
	<keyref name="dhost_keyref" refer="tns:host_key">
		<selector xpath="tns:in/tns:connection"/>
		<field xpath="@host2"/>
	</keyref>
	
        



 </element>
 

<complexType name="dp2_nfvType">
	<sequence>
		<element name="catalog" type="tns:catalogType" />
		<element name="nf_fg" type="tns:nf_fgType" minOccurs="0" maxOccurs="unbounded">
		</element>
		<element name="in" type="tns:inType" />
	</sequence>
</complexType>
<complexType name="nf_fgType">
	<sequence>
		<element name="node" type="tns:nodeType" minOccurs="0" maxOccurs="unbounded">	
		</element>
	</sequence>
	<attribute name="name" type="tns:EntityName" use="required" />
	<attribute name="deploy_time" type="dateTime" use="optional" />
</complexType>

<complexType name="catalogType">
	<sequence>
			<element name="VNFT" type="tns:VNFTType" maxOccurs="unbounded" />
	</sequence>
</complexType>

<complexType name="VNFTType">
	<attribute name="name" type="tns:EntityName" use="required" />
	<attribute name="memory" type="int" use="required" />
	<attribute name="disk_storage" type="int" use="required" />
	<attribute name="func_type" type="tns:func_typeType" use="required" />
</complexType>

<simpleType name="func_typeType">
	<restriction base="string">
      <enumeration value="CACHE" />
      <enumeration value="DPI" />
      <enumeration value="FW" />
      <enumeration value="MAIL_CLIENT" />
      <enumeration value="MAIL_SERVER" />
      <enumeration value="WEB_CLIENT" />
      <enumeration value="WEB_SERVER" />
      <enumeration value="VPN" />
      <enumeration value="SPAM" />
      <enumeration value="NAT" />
    </restriction>
</simpleType>


<complexType name="nodeType">
	<sequence>
		<element name="link" type="tns:linkType" minOccurs="0" maxOccurs="unbounded" />
		<element name="host" type="tns:EntityName" minOccurs="0" />
	</sequence>	
	<attribute name="name" type="tns:EntityName" use="required" />
	<attribute name="nffg_name" type="tns:EntityName" use="required" />
	<attribute name="VNFT" type="tns:EntityName" use="required" />
</complexType>

<complexType name="linkType">
	<attribute name="name" type="tns:EntityName" use="required" />
	<attribute name="source_node" type="tns:EntityName" use="required" />
	<attribute name="dest_node" type="tns:EntityName" use="required" />
	<attribute name="min_through" type="float" default="0" />
	<attribute name="max_latency" type="int" default="0" />
</complexType>

<complexType name="inType">
	<sequence>
		<element name="host" type="tns:hostType" minOccurs="0" maxOccurs="unbounded" />
		<element name="connection" type="tns:connectionType" minOccurs="0" maxOccurs="unbounded" />		
	</sequence>
</complexType>
<complexType name="hostType">
	<sequence>
		<element name="node" type="tns:EntityName" minOccurs="0" maxOccurs="unbounded" />
	</sequence>
	<attribute name="name" type="tns:EntityName" use="required" />
	<attribute name="max_vnf" type="positiveInteger" use="required" />
	<attribute name="memory" type="int" />
	<attribute name="disk_storage" type="int" />
</complexType>

<complexType name="connectionType">
	<attribute name="host1" type="tns:EntityName" use="required" />
	<attribute name="host2" type="tns:EntityName" use="required" />
	<attribute name="avg_through" type="float" />
	<attribute name="avg_latency" type="int" />
</complexType>


<!-- the name of the entity (a string made of alphanumeric characters only, where the first character is alphabetic). -->
<simpleType name="EntityName">
    <restriction base="string">
			<pattern value="[a-zA-Z]+[a-zA-Z0-9]*" />
	</restriction>
</simpleType>

</schema>

=== mariaserena/DP_Assignments/lab1/lab1/xsd/nfvInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xsd>
<dp2_nfv
	xmlns="http://NFV.dp2.polito.it"  
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://NFV.dp2.polito.it nfvInfo.xsd">
	
	<catalog>
		<VNFT name="NAT1" memory="25" disk_storage="310" func_type="NAT"></VNFT>
		<VNFT name="WebServer1" memory="76" disk_storage="510" func_type="WEB_SERVER"></VNFT>
		<VNFT name="WebClient1" memory="20" disk_storage="400" func_type="WEB_CLIENT"></VNFT>
		<VNFT name="Firewall1" memory="310" disk_storage="1900" func_type="FW"></VNFT>
	</catalog>

	
	<nf_fg name="mynffg" deploy_time="2017-10-21T09:00:00">
		<node name="node1" VNFT="WebClient1" nffg_name="mynffg">
			<link name="l1" source_node="node1" dest_node="node2" min_through="0" max_latency="5"></link>
			<host>h1</host>
		</node>
		<node name="node2" VNFT="NAT1" nffg_name="mynffg">
			<link name="l2" source_node="node2" dest_node="node3" min_through="0" max_latency="5"></link>
			<link name="l6" source_node="node2" dest_node="node1" min_through="0" max_latency="5"></link>
			<host>h2</host>
		</node>
		<node name="node3" VNFT="Firewall1" nffg_name="mynffg">
			<link name="l3" source_node="node3" dest_node="node4" min_through="0" max_latency="5"></link>
			<link name="l5" source_node="node3" dest_node="node2" min_through="0" max_latency="5"></link>
			<host>h3</host>		
		</node>
		<node name="node4"  VNFT="WebServer1" nffg_name="mynffg">
			<link name="l4" source_node="node4" dest_node="node3" ></link>
			<host>h4</host>
		</node>
		
	</nf_fg>
	
	<in>
		<host name="h1" max_vnf="1" memory="2000" disk_storage="4000">
			<node>node1</node>
		</host>
		<host name="h2" max_vnf="1" memory="2000" disk_storage="4000">
			<node>node2</node>
		</host>
		<host name="h3" max_vnf="1" memory="2000" disk_storage="4000">
			<node>node3</node>
		</host>
		<host name="h4" max_vnf="1" memory="2000" disk_storage="4000">
			<node>node4</node>
		</host>
		<connection host1="h1" host2="h2" avg_through="2" avg_latency="2"></connection>
		<connection host1="h2" host2="h3" avg_through="2" avg_latency="2"></connection>
		<connection host1="h3" host2="h4" avg_through="2" avg_latency="2"></connection>
		<connection host1="h4" host2="h3" avg_through="2" avg_latency="2"></connection>
		<connection host1="h3" host2="h2" avg_through="2" avg_latency="2"></connection>
		<connection host1="h2" host2="h1" avg_through="2" avg_latency="2"></connection>
	</in>

</dp2_nfv>
